### ISSUE TITLE
Fix for right edge of antialiased polygon

### ISSUE THREAD

**Issue by erich666** [erich666/GraphicsGems#26]
From Andrew Bainbridge:

On page 665 of volume 1 there's a line of code that looks like:
  if (x>xLmax && x<xRmin)

It should read:
  if (x>xLmax && xr<xRmin)

The original code leaves jaggies on the right hand edges of polygons.

![jaggies_be_gone](https://user-images.githubusercontent.com/803995/42003349-0e6c6564-7a39-11e8-9c10-66958c344e33.png)

Also, there's a tiny error in the errata! I'm looking at:
https://github.com/erich666/GraphicsGems/blob/master/Errata.GraphicsGems

There's an existing entry for page 665, but it is out of order. Shock horror.

**Comment by erich666** [comment]
Question: there are two places where this line of code appears, 196 and 229 in the file https://github.com/erich666/GraphicsGems/blob/master/gems/AAPolyScan.c

Should it be fixed in both locations, I assume?

**Comment by abainbridge** [comment]
Good spot. I believe it does need to be fixed in both places. However, in my case I'm not doing hidden surface removal, so I don't use the mask at all (see comment on line 209). I haven't tested the code at line 229, hence why I missed it. 

The reason it needs to be changed to xr is as follows: Look at the diagram of subpixel coverage on page 81 of the book. "pixelLeft" in the diagram is "x" in the code. "pixelRight" is "xr". The comment says, "shortcut for common case of fully covered pixel". Following the diagram, you would need to check all of the values from the xLeft and xRight arrays against pixelLeft and pixelRight to see if the entire pixel was covered. The code speeds this up by maintaining the xLmax, xRmin variables which store the max value from xLeft and min value from xRight respectively. Hopefully you can then see that we need to compare **_xr_** against xRmin.

The same argument is true in both the line 196 and 229 cases.

**Comment by erich666** [comment]
I think I'm convinced by your arguments, and your image (i.e., you actually tested this fix). I've checked in this fix.
