### ISSUE TITLE
How to use the C code of implicit.m in ~/gemsiv?

### ISSUE THREAD

**Issue by JamKuo** [erich666/GraphicsGems#33]
I try to run it in Xcode on Mac, but so many errors have happened!

**Comment by erich666** [comment]
I wouldn't doubt it. The code's 26 years old and in C, not C++, so can mostly be thought of as pseudocode at this point. If you do take the time to fix the function headers (tedious, but easy) and other compilation bugs, please do submit an update.

Closing - won't personally fix.

**Comment by erich666** [comment]
JamKuo,

I'm looking at this one again. Since I don't know the errors you're finding, there's not a lot I can do. Could you please write me directly at erich@acm.org and send on what problems you've found? Like I say, you'll need to, as a start, likely convert headers to C++. I think the code itself works, AFAIK, but needs conversion.

Eric
